"stash" new git submodules; system-server proxy

diff --git a/_parent b/_parent
--- a/_parent
+++ b/_parent
@@ -7,8 +7,8 @@ else
 fi
 parent="$(ps -o ppid= -p "$pid" ||:)"
 if [ "$parent" = "" ]; then
-    echo>&2 "$(basename $0): parent not found. Probably, process is dead"
+    echo>&2 "$(basename "$0"): parent not found. Probably, process is dead"
     exit 1
 fi
-parent=$(echo "$parent" |sed -r 's/(^ +)|( +$)//g') # trim whitespaces
+parent=$(echo "$parent" |sed -r 's/(^ +)|( +$)//g')  # trim whitespaces
 echo "$parent"
