.

diff --git a/init-py-venv b/init-py-venv
--- a/init-py-venv
+++ b/init-py-venv
@@ -1,23 +1,40 @@
 #!/bin/sh
 set -e
-version2="$1"
-[ "$version2" != "" ] || version2=3
+version="$1"
 
-python="python$version2"
-reg="^Python ([0-9]+(\\.[0-9]+){2})$"
-version3="$($python --version)"
-if echo "$version3" |grep -Eq "$reg"; then
-    version3="$(echo "$version3" |sed -r "s/$reg/\1/")"
+if [ ! "$version" ]; then
+    version=3
+fi
+
+python="python$version"
+reg="^Python ((([0-9]+)\\.[0-9]+)\\.[0-9]+)$"
+version_str="$($python --version)"
+if echo "$version_str" |grep -Eq "$reg"; then
+    version1="$(echo "$version_str" |sed -r "s/$reg/\3/")"
+    version2="$(echo "$version_str" |sed -r "s/$reg/\2/")"
+    version3="$(echo "$version_str" |sed -r "s/$reg/\1/")"
 else
-    echo>&2 "Invalid version: $version3"
+    echo>&2 "Invalid version: $version_str"
     exit 1
 fi
 
 mkdir -p .venv
-$python -m venv ".venv/$version3"
-"./.venv/$version3/bin/pip" install --upgrade pip setuptools wheel
+venv=".venv/$version3"
+$python -m venv "$venv"
+pip="./$venv/bin/pip"
+"$pip" install --upgrade pip setuptools wheel
 
-requirements="requirements.txt"
-if [ -f "$requirements" ]; then
-    "./.venv/$version3/bin/pip" install -r "$requirements"
+requirements=""
+for candidate in                     \
+        "requirements.txt"           \
+        "requirements-$version1.txt" \
+        "requirements-$version2.txt" \
+        "requirements-$version3.txt" \
+        ; do
+    if [ -f "$candidate" ]; then
+        requirements="$candidate"
+    fi
+done
+if [ "$requirements" ]; then
+    "$pip" install -r "$requirements"
 fi
