.

diff --git a/init-py-venv b/init-py-venv
--- a/init-py-venv
+++ b/init-py-venv
@@ -1,20 +1,23 @@
 #!/bin/sh
 set -e
+version2="$1"
+[ "$version2" != "" ] || version2=3
 
+python="python$version2"
 reg="^Python ([0-9]+(\\.[0-9]+){2})$"
-version="$(python3 --version)"
-if echo "$version" |grep -Eq "$reg"; then
-    version="$(echo "$version" |sed -r "s/$reg/\1/")"
+version3="$($python --version)"
+if echo "$version3" |grep -Eq "$reg"; then
+    version3="$(echo "$version3" |sed -r "s/$reg/\1/")"
 else
-    echo>&2 "Invalid version: $version"
+    echo>&2 "Invalid version: $version3"
     exit 1
 fi
 
 mkdir -p .venv
-python3 -m venv ".venv/$version"
-"./.venv/$version/bin/pip" install --upgrade pip
+$python -m venv ".venv/$version3"
+"./.venv/$version3/bin/pip" install --upgrade pip setuptools wheel
 
 requirements="requirements.txt"
 if [ -f "$requirements" ]; then
-    "./.venv/$version/bin/pip" install -r "$requirements"
+    "./.venv/$version3/bin/pip" install -r "$requirements"
 fi
