bit safer `system-server`

diff --git a/system-server b/system-server
--- a/system-server
+++ b/system-server
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -e
 _highlander
 
 url=127.0.0.1
@@ -7,8 +8,10 @@ port=8703
 reg='^\[[^]]+\]  "[^G]*GET[^/]+/([^"]+[0-9a-zA-Z])[^"0-9a-zA-Z]*".*$'
 # reg='^\[[^]]+\]  "[^G]*GET[^/]+/([[:print:]]+)[^[[:print:]]].*$'
 # grep + sed don't work..
-http-server -a $url -p $port 2>/dev/null |while read line; do
+http-server -a $url -p $port -d false -i false 2>/dev/null |while read line; do
     if [ "$(echo "$line" |grep -E "$reg")" ]; then
+        if [ "$(echo "$line" |grep -E 'Error \(404\): "Not found"$')" ]; then continue; fi
+
         uri="$(echo "$line" |sed -r "s~$reg~\1~")"
         # length=$(echo "$uri" |awk '{print length($0)}')
         # uri="$(echo "$uri" |cut -c1-$(($length-5)))"
